package storage

// The inventory is explicit: adding a table, column or ownership link requires
// a migration decision. FTS internals are rebuilt; planner statistics are metadata.
var userStorageMigrationTables = map[string]migrationTableRule{
	"gofer_storage_layout":            {migrationGenerated, ``, "singleton,layout_version,layout_id,manifest_digest"},
	"account_caldav_configs":          {migrationLocal, `r.user_id`, "account_id,user_id,base_url,username,encrypted_password,use_account_credentials,updated_at"},
	"account_contact_address_books":   {migrationLocal, `r.user_id`, "account_id,user_id,id,url,name,is_default,last_sync_token,last_success_at,last_error,created_at,updated_at"},
	"account_contact_sync_configs":    {migrationLocal, `r.user_id`, "account_id,user_id,provider,enabled,base_url,addressbook_url,username,encrypted_password,last_sync_token,last_started_at,last_success_at,last_import_count,last_error,created_at,updated_at"},
	"account_signature_settings":      {migrationLocal, `(SELECT a.user_id FROM @accounts a WHERE a.id=r.account_id)`, "account_id,new_signature_id,reply_signature_id,forward_signature_id,new_enabled,reply_enabled,forward_enabled,reply_placement,forward_placement,updated_at"},
	"accounts":                        {migrationLocal, `r.user_id`, "id,user_id,provider,provider_account_id,email_address,display_name,color,initials,imap_host,imap_port,imap_tls_mode,smtp_host,smtp_port,smtp_tls_mode,username,encrypted_password,auth_method,smtp_username,encrypted_smtp_password,email_sync_enabled,email_sync_error,email_sync_error_at,is_deleting,created_at,updated_at"},
	"app_settings":                    {migrationPreferences, `r.user_id`, "user_id,key,value,updated_at"},
	"attachments":                     {migrationLocal, `(SELECT a.user_id FROM @messages m JOIN @accounts a ON a.id=m.account_id WHERE m.id=r.message_id)`, "id,message_id,filename,content_type,size_bytes,content_id,inline,storage_path,sha256,provider_remote_id"},
	"auth_challenges":                 {migrationCentral, ``, "id,user_id,session_id,challenge_hash,nonce_hash,purpose,origin,attempts,max_attempts,payload_ciphertext,created_at,expires_at,consumed_at"},
	"auth_events":                     {migrationCentral, ``, "id,occurred_at,actor_user_id,subject_user_id,session_id,request_id,event_type,success,reason,user_agent,source_hash,metadata_json"},
	"auth_identities":                 {migrationCentral, ``, "id,user_id,provider,issuer,subject,email,email_verified,created_at,linked_at,last_used_at"},
	"auth_system_state":               {migrationCentral, ``, "id,initialized,owner_user_id,initialized_at,setup_token_hash,setup_expires_at,setup_attempts,setup_rotated_at,cutover_version,mfa_policy,security_policy_updated_at,security_policy_updated_by,auth_event_retention_days,auth_event_retention_updated_at,auth_event_retention_updated_by"},
	"auth_throttle":                   {migrationCentral, ``, "bucket_hash,action,failure_count,first_attempt_at,last_attempt_at,blocked_until,expires_at"},
	"avatar_attempt_logs":             {migrationCentral, ``, "id,email_hash,email,provider,status,message,created_at"},
	"avatar_provider_states":          {migrationCentral, ``, "email_hash,email,provider,status,message,checked_at,created_at,updated_at"},
	"calendar_create_requests":        {migrationLocal, `r.user_id`, "user_id,request_id,source_id,request_hash,event_id,remote_id,created_at"},
	"calendar_events":                 {migrationLocal, `r.user_id`, "id,user_id,source_id,remote_id,ical_uid,series_remote_id,etag,status,summary,description,location,organizer_name,organizer_email,all_day,start_date,end_date,start_at,end_at,start_timezone,end_timezone,recurrence_json,attendees_json,response_status,online_meeting_json,html_link,provider_created_at,provider_updated_at,is_deleted,created_at,updated_at"},
	"calendar_incoming_messages":      {migrationLocal, `(SELECT a.user_id FROM @messages m JOIN @accounts a ON a.id=m.account_id WHERE m.id=r.message_id)`, "message_id,state,next_attempt_at,attempts,last_error,event_id,ical_uid,attendee,reason_code,updated_at"},
	"calendar_incoming_responses":     {migrationLocal, `r.user_id`, "user_id,source_id,ical_uid,attendee,sequence,stamp,response,updated_at"},
	"calendar_meet_drafts":            {migrationLocal, `r.user_id`, "user_id,source_id,draft_id,remote_id,conference_json,used_by,cleanup_pending,created_at"},
	"calendar_reply_jobs":             {migrationLocal, `r.user_id`, "id,user_id,source_id,resource_id,remote_id,version,response,payload,state,attempted_at,created_at"},
	"calendar_response_requests":      {migrationLocal, `r.user_id`, "user_id,source_id,remote_id,version,response,claim_id,created_at"},
	"calendar_sources":                {migrationLocal, `r.user_id`, "id,user_id,account_id,provider,remote_id,name,description,timezone,color,access_role,is_primary,is_selected,is_hidden,is_deleted,created_at,updated_at"},
	"calendar_sync_state":             {migrationLocal, `(SELECT c.user_id FROM @calendar_sources c WHERE c.id=r.source_id)`, "source_id,state,cursor_kind,cursor_value,window_start,window_end,full_sync_required,attempt_count,last_started_at,last_success_at,next_attempt_at,last_error,created_at,updated_at"},
	"calendar_teams_drafts":           {migrationLocal, `r.user_id`, "user_id,source_id,draft_id,remote_id,meeting_json,used_by,state,updated_at"},
	"contact_activity_events":         {migrationLocal, `r.user_id`, "id,user_id,event_type,email,message,event_count,created_at"},
	"contact_card_groups":             {migrationLocal, `r.user_id`, "card_id,group_id,user_id,created_at"},
	"contact_cards":                   {migrationLocal, `r.user_id`, "id,user_id,profile_id,kind,provider,account_id,address_book_id,remote_id,etag,raw_payload,raw_payload_type,sync_status,last_error,is_deleted,created_at,updated_at"},
	"contact_conflicts":               {migrationLocal, `r.user_id`, "id,user_id,profile_id,field_kind,local_value,remote_value,provider,account_id,status,created_at,updated_at"},
	"contact_fields":                  {migrationLocal, `r.user_id`, "id,user_id,profile_id,card_id,kind,label,value,normalized_value,is_primary,ordinal,source,confidence,created_at,updated_at"},
	"contact_groups":                  {migrationLocal, `r.user_id`, "id,user_id,provider,account_id,remote_id,name,color,created_at,updated_at"},
	"contact_identities":              {migrationLocal, `r.user_id`, "user_id,profile_id,kind,normalized_value,confidence,created_at,updated_at"},
	"contact_observations":            {migrationLocal, `r.user_id`, "id,user_id,profile_id,email,normalized_email,observed_name,message_count,last_seen_at,is_suppressed,suppress_auto_create,created_at,updated_at"},
	"contact_profiles":                {migrationLocal, `r.user_id`, "id,user_id,display_name,sort_name,primary_email,avatar_url,notes,origin,sync_enabled,is_deleted,created_at,updated_at"},
	"contact_sync_memberships":        {migrationLocal, `r.user_id`, "id,user_id,profile_id,account_id,address_book_id,enabled,status,last_error,created_at,updated_at"},
	"contact_sync_operations":         {migrationLocal, `r.user_id`, "id,user_id,contact_id,email,payload_json,status,attempt_count,last_error,locked_at,next_attempt_at,created_at,updated_at"},
	"folder_id_aliases":               {migrationLocal, `(SELECT a.user_id FROM @folders f JOIN @accounts a ON a.id=f.account_id WHERE f.id=r.new_id)`, "old_id,new_id,created_at"},
	"folder_thread_state":             {migrationLocal, `(SELECT a.user_id FROM @accounts a WHERE a.id=r.account_id)`, "folder_id,thread_key,head_message_id,account_id,last_message_at,thread_count,thread_is_read,thread_is_starred,thread_has_attachments,updated_at"},
	"folders":                         {migrationLocal, `(SELECT a.user_id FROM @accounts a WHERE a.id=r.account_id)`, "id,account_id,parent_id,remote_id,provider_remote_id,name,icon,role,selectable,sort_order,uid_validity,uid_next,sync_cursor,sync_progress_current,sync_progress_started_at,highest_seen_uid,highest_modseq,last_full_sync_at,last_incremental_sync_at,sync_error,total_count,unread_count,provider_count_drift_first_seen_at,provider_count_drift_last_seen_at,provider_count_drift_local_count,provider_count_drift_remote_count,provider_count_drift_cursor,provider_count_drift_confirmations,last_seen_at,missing_since,discovery_state,created_at,updated_at"},
	"gmail_message_fetch_queue":       {migrationLocal, `(SELECT a.user_id FROM @accounts a WHERE a.id=r.account_id)`, "account_id,provider_message_id,history_id,attempts,next_attempt_at,last_error,first_seen_at,updated_at"},
	"gmail_poll_state":                {migrationLocal, `(SELECT a.user_id FROM @accounts a WHERE a.id=r.account_id)`, "account_id,profile_history_id,last_checked_at,last_changed_at,last_error,consecutive_errors,created_at,updated_at"},
	"gofer_account_active_poll":       {migrationGenerated, ``, "account_id,next_due_ms,last_attempt_ns,failures,revision"},
	"gofer_account_directory":         {migrationGenerated, ``, "account_id,user_id,state,created_at,updated_at"},
	"gofer_account_poll_schedule":     {migrationGenerated, ``, "account_id,next_due_ms,revision"},
	"gofer_account_provider_retry":    {migrationGenerated, ``, "account_id,retry_until_ms"},
	"gofer_account_service_schedule":  {migrationGenerated, ``, "account_id,service,next_due_ms,revision"},
	"gofer_avatar_interests":          {migrationGenerated, ``, "email_hash,user_id"},
	"gofer_contact_queue_schedule":    {migrationGenerated, ``, "user_id,next_due_ms,revision"},
	"gofer_mailbox_credentials":       {migrationGenerated, ``, "id,account_id,user_id,provider,provider_account_id,access_token_ciphertext,refresh_token_ciphertext,key_version,token_type,expires_at,scopes,granted_scopes,revision,created_at,updated_at"},
	"gofer_provider_draft_operations": {migrationLocal, `(SELECT a.user_id FROM @accounts a WHERE a.id=r.account_id)`, "id,account_id,draft_key,kind,revision_token,mime_data,message_date,status,attempt_count,create_attempted,candidate_id,candidate_message_id,last_error,next_attempt_at"},
	"gofer_provider_draft_states":     {migrationLocal, `(SELECT a.user_id FROM @accounts a WHERE a.id=r.account_id)`, "account_id,draft_key,provider,mailbox_subject,local_message_id,folder_id,local_revision,remote_id,remote_message_id,remote_revision"},
	"gofer_provider_send_receipts":    {migrationLocal, `(SELECT a.user_id FROM @outgoing_sends s JOIN @accounts a ON a.id=s.account_id WHERE s.id=r.send_id)`, "send_id,provider,mailbox_subject,provider_message_id"},
	"gofer_user_cleanup_receipts":     {migrationGenerated, ``, "user_id,completed_at"},
	"gofer_user_store":                {migrationGenerated, ``, "singleton,layout_version,user_id"},
	"gofer_user_store_directory":      {migrationGenerated, ``, "user_id,state,created_at,updated_at"},
	"imap_draft_operations":           {migrationLocal, `(SELECT a.user_id FROM @accounts a WHERE a.id=r.account_id)`, "id,account_id,draft_key,kind,revision_token,mime_data,message_date,status,attempt_count,last_error,locked_at,next_attempt_at,created_at,updated_at"},
	"imap_draft_states":               {migrationLocal, `(SELECT a.user_id FROM @accounts a WHERE a.id=r.account_id)`, "account_id,draft_key,local_message_id,folder_id,folder_remote_name,remote_uid,uid_validity,created_at,updated_at"},
	"label_aliases":                   {migrationLocal, `(SELECT a.user_id FROM @accounts a WHERE a.id=r.account_id)`, "account_id,provider_type,provider_id,display_name,color,source,created_at,updated_at"},
	"label_mutation_queue":            {migrationLocal, `(SELECT a.user_id FROM @accounts a WHERE a.id=r.account_id)`, "id,account_id,message_id,folder_id,provider_type,operation,label_name,attempts,next_attempt_at,last_error,created_at,updated_at"},
	"label_sync_state":                {migrationLocal, `(SELECT a.user_id FROM @accounts a WHERE a.id=r.account_id)`, "account_id,provider_type,scope,cursor,last_full_sync_at,last_success_at,last_error,last_run_started_at,last_run_finished_at,last_total_messages,last_synced_messages,last_with_labels,last_without_labels,last_missing_provider_messages,last_skipped_messages,last_failed_messages,last_pending_mutations,updated_at"},
	"labels":                          {migrationLocal, `(SELECT a.user_id FROM @accounts a WHERE a.id=r.account_id)`, "id,account_id,name,color,provider_id,provider_type,is_system,updated_at"},
	"mail_security_exceptions":        {migrationCentral, ``, "id,kind,protocol,host,port,created_by,created_at"},
	"message_folder_state":            {migrationLocal, `(SELECT a.user_id FROM @messages m JOIN @accounts a ON a.id=m.account_id WHERE m.id=r.message_id)`, "message_id,folder_id,remote_uid,is_read,is_starred,is_flagged,is_draft,is_deleted,is_archived,synced_at"},
	"message_labels":                  {migrationLocal, `(SELECT a.user_id FROM @messages m JOIN @accounts a ON a.id=m.account_id WHERE m.id=r.message_id)`, "message_id,label_id"},
	"message_mutations":               {migrationLocal, `(SELECT a.user_id FROM @accounts a WHERE a.id=r.account_id)`, "id,account_id,message_id,folder_id,provider_type,kind,target_value,destination_folder_id,source_uid_validity,status,attempt_count,last_error,locked_at,next_attempt_at,created_at,updated_at"},
	"message_recipients":              {migrationLocal, `(SELECT a.user_id FROM @messages m JOIN @accounts a ON a.id=m.account_id WHERE m.id=r.message_id)`, "id,message_id,kind,name,email"},
	"message_references":              {migrationLocal, `(SELECT a.user_id FROM @messages m JOIN @accounts a ON a.id=m.account_id WHERE m.id=r.message_id)`, "message_id,referenced_message_id,ordinal"},
	"message_search":                  {migrationSearch, `(SELECT a.user_id FROM @accounts a WHERE a.id=r.account_id)`, "account_id,thread_key,subject,sender,recipients,snippet,body,attachment_names"},
	"message_search_config":           {migrationSearchShadow, ``, "k,v"},
	"message_search_content":          {migrationSearchShadow, ``, "id,c0,c1,c2,c3,c4,c5,c6,c7"},
	"message_search_data":             {migrationSearchShadow, ``, "id,block"},
	"message_search_docsize":          {migrationSearchShadow, ``, "id,sz"},
	"message_search_idx":              {migrationSearchShadow, ``, "segid,term,pgno"},
	"messages":                        {migrationLocal, `(SELECT a.user_id FROM @accounts a WHERE a.id=r.account_id)`, "id,account_id,remote_message_id,internet_message_id,message_id_normalized,thread_id,thread_parent_id,provider_thread_id,in_reply_to,references,normalized_subject,subject,from_name,from_email,date_sent,date_received,snippet,preview_text,body_text_path,body_html_path,body_html_original_path,raw_path,size_bytes,has_attachments,created_at,updated_at"},
	"oauth_account_flows":             {migrationCentral, ``, "state_hash,user_id,session_token_hash,provider,form_data,expires_at,created_at"},
	"oauth_accounts":                  {migrationOAuth, `(SELECT a.user_id FROM @accounts a WHERE a.id=r.account_id)`, "id,account_id,provider,provider_account_id,access_token,refresh_token,access_token_ciphertext,refresh_token_ciphertext,key_version,token_type,expires_at,scopes,created_at,updated_at"},
	"outgoing_sends":                  {migrationLocal, `(SELECT a.user_id FROM @accounts a WHERE a.id=r.account_id)`, "id,account_id,message_id,draft_id,transport,envelope_from,envelope_recipients,mime_data,message_json,send_after,next_attempt_at,is_scheduled,status,attempt_count,last_error,locked_at,sent_message_id,sent_copy_status,sent_copy_attempt_count,sent_copy_last_error,sent_copy_locked_at,sent_copy_next_attempt_at,sent_copy_uid,sent_copy_uid_validity,created_at,updated_at"},
	"password_credentials":            {migrationCentral, ``, "user_id,password_hash,must_change,created_at,changed_at,reset_at"},
	"recovery_codes":                  {migrationCentral, ``, "id,user_id,batch_id,code_hash,created_at,used_at,revoked_at"},
	"remote_content_messages":         {migrationLocal, `(SELECT a.user_id FROM @messages m JOIN @accounts a ON a.id=m.account_id WHERE m.id=r.message_id)`, "message_id"},
	"remote_content_senders":          {migrationLegacySenders, ``, "sender_email,created_at"},
	"schema_version":                  {migrationSchema, ``, "version,applied_at"},
	"sender_avatars":                  {migrationCentral, ``, "email_hash,email,source,gravatar_status,gravatar_checked_at,bimi_status,bimi_checked_at,status,content_type,image_data,storage_path,fetched_at,expires_at,next_retry_at,error,created_at,updated_at"},
	"sessions":                        {migrationCentral, ``, "id,user_id,token_hash,auth_version,authentication_method,assurance_level,user_agent,authenticated_at,last_used_at,idle_expires_at,absolute_expires_at,step_up_at,step_up_method,revoked_at,revoked_by,revocation_reason,created_at"},
	"signatures":                      {migrationLocal, `r.user_id`, "id,user_id,name,html_body,text_body,created_at,updated_at"},
	"sqlite_sequence":                 {migrationSequence, ``, "name,seq"},
	"sync_state":                      {migrationLocal, `(SELECT a.user_id FROM @accounts a WHERE a.id=r.account_id)`, "id,account_id,folder_id,cursor,last_success_at,last_error,updated_at"},
	"threads":                         {migrationLocal, `(SELECT a.user_id FROM @accounts a WHERE a.id=r.account_id)`, "id,account_id,subject,normalized_subject,root_message_id,last_message_at,message_count,unread_count,created_at,updated_at"},
	"totp_credentials":                {migrationCentral, ``, "id,user_id,encrypted_seed,key_version,algorithm,digits,period,issuer,last_accepted_step,enabled,created_at,last_used_at,revoked_at"},
	"unresolved_references":           {migrationLocal, `(SELECT a.user_id FROM @accounts a WHERE a.id=r.account_id)`, "account_id,referenced_message_id,child_message_id,ordinal,created_at"},
	"user_enrollment_tokens":          {migrationCentral, ``, "id,user_id,created_by,token_hash,purpose,created_at,expires_at,used_at,revoked_at"},
	"users":                           {migrationUsers, `r.id`, "id,username,username_normalized,name,avatar_url,status,auth_version,mfa_required,last_login_at,disabled_at,disabled_by,password_reset_requested_at,deletion_pending,deletion_started_at,deletion_started_by,user_type,is_admin,created_at,updated_at"},
	"web_push_subscriptions":          {migrationCentral, ``, "endpoint,user_id,p256dh,auth,user_agent,last_error,revision,created_at,updated_at"},
	"webauthn_credentials":            {migrationCentral, ``, "id,user_id,credential_id,public_key,sign_count,aaguid,transports,attachment,backup_eligible,backup_state,name,created_at,last_used_at,revoked_at,credential_ciphertext,key_version,rp_id,flags,clone_warning"},
	"webauthn_users":                  {migrationCentral, ``, "user_id,rp_id,user_handle,created_at"},
	"sqlite_stat1":                    {migrationPlanner, "", "tbl,idx,stat"},
	"sqlite_stat4":                    {migrationPlanner, "", "tbl,idx,neq,nlt,ndlt,sample"},
}

// Required links come from the runtime schema, rather than trusting that a
// historical source actually declared every foreign key. Composite keys stay
// together; nullable links retain SQLite foreign-key semantics.
var userStorageMigrationLinks = []migrationLink{
	{"account_caldav_configs", "users", []string{"user_id"}, []string{"id"}},
	{"account_caldav_configs", "accounts", []string{"account_id"}, []string{"id"}},
	{"account_contact_address_books", "users", []string{"user_id"}, []string{"id"}},
	{"account_contact_address_books", "accounts", []string{"account_id"}, []string{"id"}},
	{"account_contact_sync_configs", "users", []string{"user_id"}, []string{"id"}},
	{"account_contact_sync_configs", "accounts", []string{"account_id"}, []string{"id"}},
	{"account_signature_settings", "signatures", []string{"forward_signature_id"}, []string{"id"}},
	{"account_signature_settings", "signatures", []string{"reply_signature_id"}, []string{"id"}},
	{"account_signature_settings", "signatures", []string{"new_signature_id"}, []string{"id"}},
	{"account_signature_settings", "accounts", []string{"account_id"}, []string{"id"}},
	{"accounts", "users", []string{"user_id"}, []string{"id"}},
	{"app_settings", "users", []string{"user_id"}, []string{"id"}},
	{"attachments", "messages", []string{"message_id"}, []string{"id"}},
	{"auth_challenges", "sessions", []string{"session_id"}, []string{"id"}},
	{"auth_challenges", "users", []string{"user_id"}, []string{"id"}},
	{"auth_events", "sessions", []string{"session_id"}, []string{"id"}},
	{"auth_events", "users", []string{"subject_user_id"}, []string{"id"}},
	{"auth_events", "users", []string{"actor_user_id"}, []string{"id"}},
	{"auth_identities", "users", []string{"user_id"}, []string{"id"}},
	{"auth_system_state", "users", []string{"auth_event_retention_updated_by"}, []string{"id"}},
	{"auth_system_state", "users", []string{"security_policy_updated_by"}, []string{"id"}},
	{"auth_system_state", "users", []string{"owner_user_id"}, []string{"id"}},
	{"calendar_create_requests", "calendar_sources", []string{"source_id"}, []string{"id"}},
	{"calendar_create_requests", "users", []string{"user_id"}, []string{"id"}},
	{"calendar_events", "calendar_sources", []string{"source_id"}, []string{"id"}},
	{"calendar_events", "users", []string{"user_id"}, []string{"id"}},
	{"calendar_incoming_messages", "messages", []string{"message_id"}, []string{"id"}},
	{"calendar_incoming_responses", "calendar_sources", []string{"source_id"}, []string{"id"}},
	{"calendar_incoming_responses", "users", []string{"user_id"}, []string{"id"}},
	{"calendar_meet_drafts", "calendar_sources", []string{"source_id"}, []string{"id"}},
	{"calendar_meet_drafts", "users", []string{"user_id"}, []string{"id"}},
	{"calendar_reply_jobs", "calendar_sources", []string{"source_id"}, []string{"id"}},
	{"calendar_reply_jobs", "users", []string{"user_id"}, []string{"id"}},
	{"calendar_reply_jobs", "outgoing_sends", []string{"id"}, []string{"id"}},
	{"calendar_response_requests", "calendar_sources", []string{"source_id"}, []string{"id"}},
	{"calendar_response_requests", "users", []string{"user_id"}, []string{"id"}},
	{"calendar_sources", "accounts", []string{"account_id"}, []string{"id"}},
	{"calendar_sources", "users", []string{"user_id"}, []string{"id"}},
	{"calendar_sync_state", "calendar_sources", []string{"source_id"}, []string{"id"}},
	{"calendar_teams_drafts", "calendar_sources", []string{"source_id"}, []string{"id"}},
	{"calendar_teams_drafts", "users", []string{"user_id"}, []string{"id"}},
	{"contact_activity_events", "users", []string{"user_id"}, []string{"id"}},
	{"contact_card_groups", "users", []string{"user_id"}, []string{"id"}},
	{"contact_card_groups", "contact_groups", []string{"group_id"}, []string{"id"}},
	{"contact_card_groups", "contact_cards", []string{"card_id"}, []string{"id"}},
	{"contact_cards", "contact_profiles", []string{"profile_id"}, []string{"id"}},
	{"contact_cards", "users", []string{"user_id"}, []string{"id"}},
	{"contact_conflicts", "contact_profiles", []string{"profile_id"}, []string{"id"}},
	{"contact_conflicts", "users", []string{"user_id"}, []string{"id"}},
	{"contact_fields", "contact_cards", []string{"card_id"}, []string{"id"}},
	{"contact_fields", "contact_profiles", []string{"profile_id"}, []string{"id"}},
	{"contact_fields", "users", []string{"user_id"}, []string{"id"}},
	{"contact_groups", "users", []string{"user_id"}, []string{"id"}},
	{"contact_identities", "contact_profiles", []string{"profile_id"}, []string{"id"}},
	{"contact_identities", "users", []string{"user_id"}, []string{"id"}},
	{"contact_observations", "users", []string{"user_id"}, []string{"id"}},
	{"contact_profiles", "users", []string{"user_id"}, []string{"id"}},
	{"contact_sync_memberships", "contact_profiles", []string{"profile_id"}, []string{"id"}},
	{"contact_sync_memberships", "users", []string{"user_id"}, []string{"id"}},
	{"contact_sync_operations", "users", []string{"user_id"}, []string{"id"}},
	{"folder_id_aliases", "folders", []string{"new_id"}, []string{"id"}},
	{"folder_thread_state", "accounts", []string{"account_id"}, []string{"id"}},
	{"folder_thread_state", "messages", []string{"head_message_id"}, []string{"id"}},
	{"folder_thread_state", "folders", []string{"folder_id"}, []string{"id"}},
	{"folders", "folders", []string{"parent_id"}, []string{"id"}},
	{"folders", "accounts", []string{"account_id"}, []string{"id"}},
	{"gmail_message_fetch_queue", "accounts", []string{"account_id"}, []string{"id"}},
	{"gmail_poll_state", "accounts", []string{"account_id"}, []string{"id"}},
	{"gofer_account_active_poll", "gofer_account_directory", []string{"account_id"}, []string{"account_id"}},
	{"gofer_account_poll_schedule", "gofer_account_directory", []string{"account_id"}, []string{"account_id"}},
	{"gofer_account_provider_retry", "gofer_account_directory", []string{"account_id"}, []string{"account_id"}},
	{"gofer_account_service_schedule", "gofer_account_directory", []string{"account_id"}, []string{"account_id"}},
	{"gofer_avatar_interests", "users", []string{"user_id"}, []string{"id"}},
	{"gofer_avatar_interests", "sender_avatars", []string{"email_hash"}, []string{"email_hash"}},
	{"gofer_contact_queue_schedule", "users", []string{"user_id"}, []string{"id"}},
	{"gofer_mailbox_credentials", "users", []string{"user_id"}, []string{"id"}},
	{"gofer_mailbox_credentials", "gofer_account_directory", []string{"account_id"}, []string{"account_id"}},
	{"gofer_provider_draft_operations", "gofer_provider_draft_states", []string{"account_id", "draft_key"}, []string{"account_id", "draft_key"}},
	{"gofer_provider_draft_states", "messages", []string{"local_message_id"}, []string{"id"}},
	{"gofer_provider_draft_states", "accounts", []string{"account_id"}, []string{"id"}},
	{"gofer_provider_send_receipts", "outgoing_sends", []string{"send_id"}, []string{"id"}},
	{"imap_draft_operations", "imap_draft_states", []string{"account_id", "draft_key"}, []string{"account_id", "draft_key"}},
	{"imap_draft_states", "messages", []string{"local_message_id"}, []string{"id"}},
	{"imap_draft_states", "accounts", []string{"account_id"}, []string{"id"}},
	{"label_aliases", "accounts", []string{"account_id"}, []string{"id"}},
	{"label_mutation_queue", "messages", []string{"message_id"}, []string{"id"}},
	{"label_mutation_queue", "accounts", []string{"account_id"}, []string{"id"}},
	{"label_sync_state", "accounts", []string{"account_id"}, []string{"id"}},
	{"labels", "accounts", []string{"account_id"}, []string{"id"}},
	{"message_folder_state", "folders", []string{"folder_id"}, []string{"id"}},
	{"message_folder_state", "messages", []string{"message_id"}, []string{"id"}},
	{"message_labels", "labels", []string{"label_id"}, []string{"id"}},
	{"message_labels", "messages", []string{"message_id"}, []string{"id"}},
	{"message_mutations", "messages", []string{"message_id"}, []string{"id"}},
	{"message_mutations", "accounts", []string{"account_id"}, []string{"id"}},
	{"message_recipients", "messages", []string{"message_id"}, []string{"id"}},
	{"message_references", "messages", []string{"message_id"}, []string{"id"}},
	{"messages", "messages", []string{"thread_parent_id"}, []string{"id"}},
	{"messages", "accounts", []string{"account_id"}, []string{"id"}},
	{"oauth_account_flows", "users", []string{"user_id"}, []string{"id"}},
	{"oauth_accounts", "accounts", []string{"account_id"}, []string{"id"}},
	{"outgoing_sends", "messages", []string{"message_id"}, []string{"id"}},
	{"outgoing_sends", "accounts", []string{"account_id"}, []string{"id"}},
	{"password_credentials", "users", []string{"user_id"}, []string{"id"}},
	{"recovery_codes", "users", []string{"user_id"}, []string{"id"}},
	{"remote_content_messages", "messages", []string{"message_id"}, []string{"id"}},
	{"sessions", "users", []string{"revoked_by"}, []string{"id"}},
	{"sessions", "users", []string{"user_id"}, []string{"id"}},
	{"signatures", "users", []string{"user_id"}, []string{"id"}},
	{"sync_state", "folders", []string{"folder_id"}, []string{"id"}},
	{"sync_state", "accounts", []string{"account_id"}, []string{"id"}},
	{"threads", "messages", []string{"root_message_id"}, []string{"id"}},
	{"threads", "accounts", []string{"account_id"}, []string{"id"}},
	{"totp_credentials", "users", []string{"user_id"}, []string{"id"}},
	{"unresolved_references", "messages", []string{"child_message_id"}, []string{"id"}},
	{"unresolved_references", "accounts", []string{"account_id"}, []string{"id"}},
	{"user_enrollment_tokens", "users", []string{"created_by"}, []string{"id"}},
	{"user_enrollment_tokens", "users", []string{"user_id"}, []string{"id"}},
	{"users", "users", []string{"deletion_started_by"}, []string{"id"}},
	{"users", "users", []string{"disabled_by"}, []string{"id"}},
	{"web_push_subscriptions", "users", []string{"user_id"}, []string{"id"}},
	{"webauthn_credentials", "users", []string{"user_id"}, []string{"id"}},
	{"webauthn_users", "users", []string{"user_id"}, []string{"id"}},
}

// Every local copy inherits the original installation-wide high-water mark,
// including gaps left by deleted rows. Never infer it from one owner partition.
var userStorageMigrationSequences = map[string]string{
	"attachments":                     "id",
	"avatar_attempt_logs":             "id",
	"contact_activity_events":         "id",
	"gofer_provider_draft_operations": "id",
	"label_mutation_queue":            "id",
	"message_recipients":              "id",
	"messages":                        "id",
	"sync_state":                      "id",
}
